// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrifCBioADPYIRvJTFgsS9JCMARmK1DBY',
    appId: '1:472907845234:web:26973fe1e9446a62243ceb',
    messagingSenderId: '472907845234',
    projectId: 'finance-tracker-ca746',
    authDomain: 'finance-tracker-ca746.firebaseapp.com',
    databaseURL: 'https://finance-tracker-ca746-default-rtdb.firebaseio.com',
    storageBucket: 'finance-tracker-ca746.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9naQesC_EUmCSYE5CPv6Fp8sTgwfxAis',
    appId: '1:472907845234:android:fd827b26d1924c26243ceb',
    messagingSenderId: '472907845234',
    projectId: 'finance-tracker-ca746',
    databaseURL: 'https://finance-tracker-ca746-default-rtdb.firebaseio.com',
    storageBucket: 'finance-tracker-ca746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaAsOdq3svoVNOVFaiCfRjNmdbXFPazg4',
    appId: '1:472907845234:ios:c250e24cd0faa0a6243ceb',
    messagingSenderId: '472907845234',
    projectId: 'finance-tracker-ca746',
    databaseURL: 'https://finance-tracker-ca746-default-rtdb.firebaseio.com',
    storageBucket: 'finance-tracker-ca746.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaAsOdq3svoVNOVFaiCfRjNmdbXFPazg4',
    appId: '1:472907845234:ios:c250e24cd0faa0a6243ceb',
    messagingSenderId: '472907845234',
    projectId: 'finance-tracker-ca746',
    databaseURL: 'https://finance-tracker-ca746-default-rtdb.firebaseio.com',
    storageBucket: 'finance-tracker-ca746.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrifCBioADPYIRvJTFgsS9JCMARmK1DBY',
    appId: '1:472907845234:web:1ffdc8e6d6bf6200243ceb',
    messagingSenderId: '472907845234',
    projectId: 'finance-tracker-ca746',
    authDomain: 'finance-tracker-ca746.firebaseapp.com',
    databaseURL: 'https://finance-tracker-ca746-default-rtdb.firebaseio.com',
    storageBucket: 'finance-tracker-ca746.firebasestorage.app',
  );
}
